version: '3'

services:
    node:
        container_name: node-api
        image: node
        ports:
            - 4000:4000
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        tty: true
        user: $CURRENT_USER
        command: ["yarn", "dev"]
